apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-pvc
  namespace: milvus
spec:
  storageClassName: retain-pd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
