apiVersion: v1
kind: ConfigMap
metadata:
  name: milvus-config
  namespace: milvus
data:
  milvus.yaml: |
    etcd:
      endpoints:
        - etcd:2379

    minio:
      address: minio
      port: 9000
      accessKeyID: minioadmin
      secretAccessKey: minioadmin
      useSSL: false
      bucketName: a-bucket
      rootPath: files
      useIAM: false
      createBucket: true
